"""推荐 Prompt 兼容导出。

运行时 Prompt 加载与组装逻辑位于 ``question_recommendation.recommender``。
"""

from .recommender import (
    QUESTION_RECOMMENDATION_PROMPT,
    QUESTION_RECOMMENDATION_SYSTEM_PROMPT,
    QUESTION_RECOMMENDATION_USER_TEMPLATE,
    _BASIC_RULES,
    _CANDIDATE_FIELD_ANALYSIS_TEMPLATE,
    _CORE_RULES,
    _EMPTY_INTENTION_BASIC_RULES,
    _METADATA_RULES,
    _NO_METADATA_RULES,
    _NORMAL_RULES,
    _OUTPUT_RULES,
    _PROMPT_DOCUMENT,
    _RECOVERY_DIRECTION_RULES,
    _RECOVERY_RULES,
    _SIMPLIFY_ANALYSIS_TEMPLATE,
    _SIMPLIFY_RULES,
    _SUBNET_RULES,
    _block_prompt,
    _build_system_prompt,
)

__all__ = [
    "QUESTION_RECOMMENDATION_PROMPT",
    "QUESTION_RECOMMENDATION_SYSTEM_PROMPT",
    "QUESTION_RECOMMENDATION_USER_TEMPLATE",
]
